# Generated by Django 2.2 on 2019-11-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0020_auto_20191108_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cvs',
        ),
        migrations.DeleteModel(
            name='job',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='user_key',
            new_name='id',
        ),
        migrations.AddField(
            model_name='registrations',
            name='cgpa',
            field=models.CharField(default='gh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrations',
            name='comapany',
            field=models.CharField(default='fg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrations',
            name='resume',
            field=models.CharField(default='fgg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrations',
            name='user_type',
            field=models.CharField(default='fdsf', max_length=100),
            preserve_default=False,
        ),
    ]
