# Generated by Django 2.2 on 2019-11-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0021_auto_20191109_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrations',
            old_name='birthday',
            new_name='company_cgpa',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='comapany',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='resume',
        ),
    ]
