# Generated by Django 2.2.2 on 2019-11-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0023_auto_20191109_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='city',
            field=models.CharField(default='Pune', max_length=100),
            preserve_default=False,
        ),
    ]
