# Generated by Django 2.2.2 on 2019-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0024_registrations_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='resume',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
